# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_merch', models.CharField(max_length=50)),
                ('merch_price', models.CharField(blank=True, default='', max_length=100)),
                ('merch_count', models.CharField(max_length=100)),
                ('merch_enabled', models.BooleanField(default=1)),
                ('merch_del', models.BooleanField(default=0)),
                ('merch_description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'order_merch_cat',
            },
        ),
        migrations.CreateModel(
            name='MerchPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, null=True, upload_to='myphoto/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('idmerch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordermodelrest.Merchandise')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
