# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordermodelrest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='merchphoto',
            table='MerchImage',
        ),
    ]
