# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordermodelrest', '0002_auto_20161130_0609'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='merchandise',
            table='MerchCat',
        ),
    ]
