# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermodelrest', '0003_auto_20161130_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchphoto',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
