# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordermodelrest', '0007_auto_20161201_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchphoto',
            name='phototype',
            field=models.CharField(default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='merchphoto',
            name='idmerch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merching', to='ordermodelrest.Merchandise'),
        ),
    ]
